# This is a basic workflow to help you get started with Actions and CRON

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow every fifteen minutes as per CRON
  schedule:
    - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sayHello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello! ${{ inputs.name }}"
